apiVersion: apps/vi
kind: Deployment
metadata:
  name: portalservice-deployment
  labels:
    app: portal-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-service
  template:
    metadata:
      labels:
        app: portal-service
    spec: 
      containers:
      - name : portalservice-container
        image:
        imagePullPolicy: 
        ports:
        - containerPort: 8080
        resources: 
          requests: 
            cpu: {{ default "0.5"}}
            memory: {{ default "512Mi"}}
          limits:
            cpu: {{ default "1"}}
            memory: {{ default "1024Mi"}}
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
                
          
            