apiVersion: v1
kind: Service
metadata:
  name: portalservice
  labels:
    app: portal-service
spec:
  selector:
    app: portal-service
  type: LoadBalancer
  ports: 
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31000
  
